/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionButtons: typeof import('./components/Common/ActionButtons.vue')['default']
    CatalogDataTable: typeof import('./components/Common/CatalogDataTable.vue')['default']
    ClassCatalog: typeof import('./components/Class/ClassCatalog.vue')['default']
    ClassHour: typeof import('./components/ClassHour.vue')['default']
    ColorsLabel: typeof import('./components/Common/ColorsLabel.vue')['default']
    DatePicker: typeof import('./components/DatePicker.vue')['default']
    LocationCatalog: typeof import('./components/Location/LocationCatalog.vue')['default']
    LoginButton: typeof import('./components/Auth/LoginButton.vue')['default']
    LogoutButton: typeof import('./components/Auth/LogoutButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./components/SideBar.vue')['default']
    TeacherCatalog: typeof import('./components/Teacher/TeacherCatalog.vue')['default']
    ThemeToggle: typeof import('./components/ThemeToggle.vue')['default']
    User: typeof import('./components/Auth/User.vue')['default']
    UserProfile: typeof import('./components/Auth/UserProfile.vue')['default']
  }
}
