/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/ClassCatalogs': RouteRecordInfo<'/ClassCatalogs', '/ClassCatalogs', Record<never, never>, Record<never, never>>,
    '/Classes': RouteRecordInfo<'/Classes', '/Classes', Record<never, never>, Record<never, never>>,
    '/ClassHours': RouteRecordInfo<'/ClassHours', '/ClassHours', Record<never, never>, Record<never, never>>,
    '/LocationCatalogs': RouteRecordInfo<'/LocationCatalogs', '/LocationCatalogs', Record<never, never>, Record<never, never>>,
    '/Locations': RouteRecordInfo<'/Locations', '/Locations', Record<never, never>, Record<never, never>>,
    '/Login': RouteRecordInfo<'/Login', '/Login', Record<never, never>, Record<never, never>>,
    '/Register': RouteRecordInfo<'/Register', '/Register', Record<never, never>, Record<never, never>>,
    '/Subjects': RouteRecordInfo<'/Subjects', '/Subjects', Record<never, never>, Record<never, never>>,
    '/Summary': RouteRecordInfo<'/Summary', '/Summary', Record<never, never>, Record<never, never>>,
    '/TeacherCatalogs': RouteRecordInfo<'/TeacherCatalogs', '/TeacherCatalogs', Record<never, never>, Record<never, never>>,
    '/Teachers': RouteRecordInfo<'/Teachers', '/Teachers', Record<never, never>, Record<never, never>>,
  }
}
