/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/Login': RouteRecordInfo<'/Login', '/Login', Record<never, never>, Record<never, never>>,
    '/p/[projectId]/ClassCatalogs': RouteRecordInfo<'/p/[projectId]/ClassCatalogs', '/p/:projectId/ClassCatalogs', { projectId: ParamValue<true> }, { projectId: ParamValue<false> }>,
    '/p/[projectId]/Classes': RouteRecordInfo<'/p/[projectId]/Classes', '/p/:projectId/Classes', { projectId: ParamValue<true> }, { projectId: ParamValue<false> }>,
    '/p/[projectId]/ClassHours': RouteRecordInfo<'/p/[projectId]/ClassHours', '/p/:projectId/ClassHours', { projectId: ParamValue<true> }, { projectId: ParamValue<false> }>,
    '/p/[projectId]/Generate': RouteRecordInfo<'/p/[projectId]/Generate', '/p/:projectId/Generate', { projectId: ParamValue<true> }, { projectId: ParamValue<false> }>,
    '/p/[projectId]/LocationCatalogs': RouteRecordInfo<'/p/[projectId]/LocationCatalogs', '/p/:projectId/LocationCatalogs', { projectId: ParamValue<true> }, { projectId: ParamValue<false> }>,
    '/p/[projectId]/Locations': RouteRecordInfo<'/p/[projectId]/Locations', '/p/:projectId/Locations', { projectId: ParamValue<true> }, { projectId: ParamValue<false> }>,
    '/p/[projectId]/Members': RouteRecordInfo<'/p/[projectId]/Members', '/p/:projectId/Members', { projectId: ParamValue<true> }, { projectId: ParamValue<false> }>,
    '/p/[projectId]/Subjects': RouteRecordInfo<'/p/[projectId]/Subjects', '/p/:projectId/Subjects', { projectId: ParamValue<true> }, { projectId: ParamValue<false> }>,
    '/p/[projectId]/TeacherCatalogs': RouteRecordInfo<'/p/[projectId]/TeacherCatalogs', '/p/:projectId/TeacherCatalogs', { projectId: ParamValue<true> }, { projectId: ParamValue<false> }>,
    '/p/[projectId]/Teachers': RouteRecordInfo<'/p/[projectId]/Teachers', '/p/:projectId/Teachers', { projectId: ParamValue<true> }, { projectId: ParamValue<false> }>,
  }
}
