/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    ClassCatalog: typeof import('./components/Class/ClassCatalog.vue')['default']
    ClassCatalogs: typeof import('./components/Class/ClassCatalogs.vue')['default']
    ClassesDataTable: typeof import('./components/Class/ClassesDataTable.vue')['default']
    ClassHour: typeof import('./components/ClassHour.vue')['default']
    ClassHourDataTable: typeof import('./components/ClassHour/ClassHourDataTable.vue')['default']
    DatePicker: typeof import('./components/DatePicker.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    LocationCatalog: typeof import('./components/Location/LocationCatalog.vue')['default']
    LocationCatalogs: typeof import('./components/Location/LocationCatalogs.vue')['default']
    LocationsDataTable: typeof import('./components/Location/LocationsDataTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./components/SideBar.vue')['default']
    SubjectsDataTable: typeof import('./components/Subject/SubjectsDataTable.vue')['default']
    TeacherCatalog: typeof import('./components/Teacher/TeacherCatalog.vue')['default']
    TeacherCatalogs: typeof import('./components/Teacher/TeacherCatalogs.vue')['default']
    TeachersDataTable: typeof import('./components/Teacher/TeachersDataTable.vue')['default']
    TimetableInitializer: typeof import('./components/TimetableInitializer.vue')['default']
  }
}
