name: cppcheck-action-test

on:
  push: # Trigger on every push

jobs:
  build:
    name: cppcheck-test
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Install Cppcheck
      - name: Install Cppcheck
        run: sudo apt-get install cppcheck -y

      # Step 3: Run Cppcheck and Collect Errors
      - name: Run Cppcheck
        run: |
          cppcheck --enable=all --inconclusive . 2> cppcheck-errors.txt
          if [ -s cppcheck-errors.txt ]; then
            cat cppcheck-errors.txt
            exit 1
          fi
      # Explanation:
      # - Collects all errors into `cppcheck-errors.txt`.
      # - Displays errors using `cat`.
      # - Fails the job if the file is not empty (`-s` checks if the file has content).

      # Step 4: Upload the Errors Report (Optional)
      - name: Upload Cppcheck Errors Report
        if: failure() # Run only if the Cppcheck step fails
        uses: actions/upload-artifact@v3
        with:
          name: cppcheck-errors
          path: cppcheck-errors.txt
